
[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "dtx_to_wif"
dynamic = ["version"]
description = "Convert handweaving files from dtx format (FiberWorks) to wif"
readme = "ReadMe.md"
authors = [
  { name="Russell Owen", email="r3owen@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"

[project.scripts]
dtx_to_wif = "dtx_to_wif:run_dtx_to_wif"
wpo_to_wif = "dtx_to_wif:run_wpo_to_wif"

[project.optional-dependencies]
# To contribute to the package.
dev = [
  "pre-commit",
  "mkdocs",
  "mkapi",
  "sphinx",
  "sphinxcontrib-napoleon",
]

[project.urls]
Homepage = "https://pypi.org/project/dtx-to-wif/"
Documentation = "https://r-owen.github.io/dtx_to_wif/"
Source = "https://github.com/r-owen/dtx_to_wif"
Issues = "https://github.com/r-owen/dtx_to_wif/issues"

[tool.setuptools_scm]
write_to = "src/dtx_to_wif/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""
